kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /drone
  path: src/github.com/justindfuller/purchase-plan

steps:
  - name: setup
    image: bash
    environment:
      GOOGLE_APPLICATION_CREDENTIALS:
        from_secret: TERRAFORM_CREDENTIALS_PURCHASE_PLAN_DEV
    commands:
      - ./scripts/setup

  - name: backend
    image: nytimes/golang-gcloud-sdk:latest
    commands:
      - ./scripts/setup
      - cd backend
      # - make test
      - make build

  - name: frontend
    image: node
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - mkdir ../backend/frontend/
      - cp -r ./build/ ../backend/frontend/
    
  - name: deploy-dev
    image: nytimes/drone-gae
    environment:
      GAE_CREDENTIALS:
        from_secret: DRONE_CREDENTIALS_DEV
    settings:
      action: deploy
      project: purchase-plan-dev
      dir: backend/cmd/server
      app_file: app.yaml
      max_versions: 10
    when:
      event: push
      branch: [main]
    depends_on:
      - frontend
      - backend

  - name: deploy-prd
    image: nytimes/drone-gae
    environment:
      GAE_CREDENTIALS:
        from_secret: DRONE_CREDENTIALS_PRD
    settings:
      action: deploy
      project: purchase-plan-prd
      dir: backend/cmd/server
      app_file: app.yaml
      max_versions: 10
    when:
      event: tag
    depends_on:
      - frontend
      - backend

  - name: slack-dev
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: drone-alerts
      link_names: true
      template: >
        {{#success build.status}}
          build {{build.link}} succeeded. Good job. <@{{build.author}}>
        {{else}}
          build {{build.link}} failed. Fix me please. <@{{build.author}}>
        {{/success}}
    depends_on:
      - deploy-dev
    when:
      events: push
      branch: [main]
      status: [ success, failure  ]

  - name: slack-prd
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      channel: drone-alerts
      link_names: true
      template: >
        {{#success build.status}}
          build {{build.link}} succeeded. Good job. <@{{build.author}}>
        {{else}}
          build {{build.link}} failed. Fix me please. <@{{build.author}}>
        {{/success}}
    depends_on:
      - deploy-prd
    when:
      events: tag
      status: [ success, failure  ]
