kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: backend
    image: nytimes/golang-gcloud-sdk:latest
    environment:
      GAE_CREDENTIALS_DEV:
        from_secret: GAE_CREDENTIALS_DEV
      SERVICE_ACCOUNT_NAME:
        from_secret: SERVICE_ACCOUNT_NAME
    commands:
      - echo -n $GAE_CREDENTIALS_DEV > ./service_account.json
      - gcloud auth activate-service-account $SERVICE_ACCOUNT_NAME --key-file=./service_account.json
      - cd api
      - make test
      - make build

  - name: frontend
    image: node
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - mkdir ../api/cmd/server/frontend/
      - cp -r ./build/ ../api/cmd/server/frontend/

  - name: deploy
    image: nytimes/drone-gae
    environment:
      GAE_CREDENTIALS:
        from_secret: GAE_CREDENTIALS_DEV
    settings:
      action: deploy
      project: purchase-saving-planner
      dir: api/cmd/server
      app_file: app.yaml
      max_versions: 10
      service: default
    when:
      event: push
      branch: [main]
    depends_on:
      - backend
      - frontend
