kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: alpine
    environment:
      GAE_CREDENTIALS_DEV:
        from_secret: GAE_CREDENTIALS_DEV
      ENV:
        from_secret: ENV
    commands:
      - ./scripts/setup

  - name: backend
    image: nytimes/golang-gcloud-sdk:latest
    commands:
      - cd backend
      # - make test
      - make build

  - name: frontend
    image: node
    commands:
      - cd frontend
      - npm ci
      - npm run build
      - mkdir ../backend/frontend/
      - cp -r ./build/ ../backend/frontend/

  - name: terraform-central-dev
    image: hashicorp/terraform:light
    commands:
      - cd ./terraform/dev
      - terraform fmt -check
      - terraform plan -input=false
      - terraform apply -input=false -auto-approve
    depends_on:
      - frontend
      - backend

  - name: deploy-central-dev
    image: nytimes/drone-gae
    environment:
      GAE_CREDENTIALS:
        from_secret: GAE_DEPLOY_CREDENTIALS_DEV
    settings:
      action: deploy
      project: purchase-plan-central-dev
      dir: backend/cmd/server
      app_file: app.yaml
      max_versions: 10
    when:
      event: push
      branch: [main]
    depends_on:
      - terraform-central-dev
